// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU70Zj9Sn0FuCBeOKxwlJ8tHtRs-inIBo',
    appId: '1:285885953934:android:1f56d97845750a023096df',
    messagingSenderId: '414961332009',
    projectId: 'instagrambasisproject-16aeb',
    storageBucket: 'desarrollo-movil-ig-clone.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJRQnLJez6AvUoWJ0YctN_Hv_hsDKYk1o',
    appId: '1:414961332009:web:8a6defd45815322c33d138',
    messagingSenderId: '414961332009',
    projectId: 'desarrollo-movil-ig-clone',
    authDomain: 'desarrollo-movil-ig-clone.firebaseapp.com',
    storageBucket: 'desarrollo-movil-ig-clone.firebasestorage.app',
    measurementId: 'G-HLFEB8JYQW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqfG3ousK5apV9S88lcshsiRaubNLQgAE',
    appId: '1:414961332009:ios:055aa575dba7aa0c33d138',
    messagingSenderId: '414961332009',
    projectId: 'desarrollo-movil-ig-clone',
    storageBucket: 'desarrollo-movil-ig-clone.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqfG3ousK5apV9S88lcshsiRaubNLQgAE',
    appId: '1:414961332009:ios:055aa575dba7aa0c33d138',
    messagingSenderId: '414961332009',
    projectId: 'desarrollo-movil-ig-clone',
    storageBucket: 'desarrollo-movil-ig-clone.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJRQnLJez6AvUoWJ0YctN_Hv_hsDKYk1o',
    appId: '1:414961332009:web:ae25e34532b9815133d138',
    messagingSenderId: '414961332009',
    projectId: 'desarrollo-movil-ig-clone',
    authDomain: 'desarrollo-movil-ig-clone.firebaseapp.com',
    storageBucket: 'desarrollo-movil-ig-clone.firebasestorage.app',
    measurementId: 'G-HFLCWW49J7',
  );

}